live_config_reload = true

import = ["~/.config/alacritty/colors/rose-pine-moon.toml"]

[env]
TERM = "alacritty"

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "main"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Light" }
bold = { family = "JetBrainsMono Nerd Font", style = "Regular" }
italic = { family = "JetBrainsMono Nerd Font", style = "Light Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Regular Italic" }
size = 15.0

[scrolling]
history = 0

[cursor]
style = "Block"
unfocused_hollow = true

[mouse]
hide_when_typing = true

[window]
decorations = "none"
dynamic_padding = false
resize_increments = true

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[debug]
render_timer = false
