import = [
    "~/.config/alacritty/colors/rose-pine-moon.toml"
]

[env]
TERM = "alacritty"

[shell]
program = "/usr/local/bin/tmux"
args = ["new-session", "-A", "-s", "main"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 16.0

[window]
dimensions = { columns = 120, lines = 48 }

[scrolling]
history = 0

[cursor]
style = "Block"
unfocused_hollow = true

[window.padding]
x = 0
y = 0
