import = [
    "~/.config/alacritty/colors/rose-pine-moon.toml"
]

[env]
TERM = "alacritty"

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "main"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Light" }
bold = { family = "JetBrainsMono Nerd Font", style = "Regular" }
italic = { family = "JetBrainsMono Nerd Font", style = "Light Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Regular Italic" }
size = 15.0

[scrolling]
history = 0

[cursor]
style = "Block"
unfocused_hollow = true

[window]
dimensions = { columns = 124, lines = 48 }
decorations = "none"

[window.padding]
x = 0
y = 0
