import = [
    "~/.config/alacritty/colors/rose-pine-moon.toml",
    "~/.config/alacritty/keybindings.toml",
]

live_config_reload = true

[env]
TERM = "alacritty"

[shell]
args    = ["new-session", "-A", "-s", "main"]
program = "/opt/homebrew/bin/tmux"

[font]
bold        = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Regular Italic" }
italic      = { family = "JetBrainsMono Nerd Font", style = "Light Italic" }
normal      = { family = "JetBrainsMono Nerd Font", style = "Light" }
size        = 15.0

[font.offset]
x = 0
y = 0

[scrolling]
history = 0

[cursor]
style            = "Block"
unfocused_hollow = true

[mouse]
hide_when_typing = true

[window]
decorations       = "none"
dynamic_padding   = false
resize_increments = true
option_as_alt     = "Onlyleft"

[window.dimensions]
columns = 120
lines   = 40

[window.padding]
x = 0
y = 0

[selection]
save_to_clipboard     = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>[]\t"

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
regex = "(mailto:|https:|http:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"
