import = [
    "~/.config/alacritty/colors/rose-pine-moon.toml",
    "~/.config/alacritty/keybindings.toml",
]

live_config_reload = true

[env]
TERM = "alacritty"

[shell]
args    = ["new-session", "-A", "-s", "main"]
program = "/opt/homebrew/bin/tmux"

[font]
bold        = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Regular Italic" }
italic      = { family = "JetBrainsMono Nerd Font", style = "Light Italic" }
normal      = { family = "JetBrainsMono Nerd Font", style = "Light" }
size        = 15.0

[font.offset]
x = 0
y = 0

[scrolling]
history = 0

[cursor]
style            = "Block"
unfocused_hollow = true

[mouse]
hide_when_typing = true

[window]
decorations       = "none"
dynamic_padding   = false
resize_increments = true
option_as_alt     = "Onlyleft"

[window.dimensions]
columns = 0
lines   = 0

[window.padding]
x = 0
y = 0

[selection]
save_to_clipboard     = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>[]\t"
