format = """
$directory\
[](fg:iris bg:overlay)\
(\
    $git_branch\
    $git_state\
    $git_status\
)\
[](fg:overlay bg:hl_low)\
(\
    $golang\
)\
[](fg:hl_low bg:base)\
$line_break\
$character\
"""

right_format = """
( $cmd_duration)\
( $status)\
"""

add_newline = true

palette = 'rose-pine-moon'

[palettes.rose-pine-moon]
base = '#232136'
surface = '#2a273f'
overlay = '#393552'
muted = '#6e6a86'
subtle = '#908caa'
text = '#e0def4'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'
hl_low = '#2a283e'
hl_med = '#44415a'
hl_high = '#56526e'

[line_break]
disable = false

[character]
success_symbol = '[ ](bold fg:iris)'
error_symbol = '[ ](bold fg:love)'
vimcmd_symbol = '[ ](bold fg:gold)'
vimcmd_replace_one_symbol = '[ ](bold fg:gold)'
vimcmd_replace_symbol = '[ ](bold fg:gold)'
vimcmd_visual_symbol = '[ ](bold fg:gold)'
disabled = false

[directory]
format = '([ $path ]($style)([ $read_only ]($read_only_style)))'
style = 'fg:base bg:iris bold'
truncation_symbol = '…'
truncation_length = 3
truncate_to_repo = true
disabled = false

[git_branch]
format = '([ $symbol$branch(:$remote_branch) ]($style))'
style = 'fg:iris bg:overlay bold'
symbol = ' '
truncation_length = 8
truncation_symbol = '…'
disabled = false

[git_state]
format = '([ $state($progress_current/$progress_total) ]($style))'
style = 'fg:iris bg:overlay bold'
disabled = false

[git_status]
format = '([$ahead_behind$all_status]($style))'
style = 'fg:iris bg:overlay bold'
conflicted = ' ${count} '
up_to_date = ' '
untracked = '󰋗 ${count} '
ahead = ' ${count}'
diverged = ' ${ahead_count}  ${behind_count}'
behind = ' ${count}'
stashed = ' ${count} '
modified = '󰛿 ${count} '
staged = '󰐗 ${count} '
renamed = '󱍸 ${count} '
deleted = '󰍶 ${count} '
disabled = false

[golang]
format = '([ $symbol($version)(\[$mod_version\]) ]($style))'
style = 'fg:muted bg:hl_low bold'
symbol = '󰟓 '

[status]
format = '[](inverted $style)[$symbol $common_meaning$signal_name$maybe_int]($style)[](inverted $style)'
style = 'fg:base bg:love bold italic'
map_symbol = true
symbol = '󱇎'
success_symbol = ''
not_executable_symbol = ''
not_found_symbol = '󰩋'
sigint_symbol = '󰹆'
signal_symbol = '󱐋'
disabled = false

[cmd_duration]
format = '[](inverted $style)[󱎫 $duration]($style)[](inverted $style)'
style = 'fg:base bg:iris bold italic'
min_time = 5000
disabled = false

[time]
format = '[](inverted $style)[󱑂 $time ]($style)'
style = 'fg:base bg:hl_high bold italic'
time_format = '%T'
utc_time_offset = 'local'
disabled = false
