format = """
$directory\
[](fg:iris bg:overlay)\
(\
    $git_branch\
    $git_state\
    $git_status\
)\
[](fg:overlay bg:hl_low)\
(\
    $python\
    $golang\
)\
[](fg:hl_low bg:base)\
$line_break\
$character\
"""

right_format = """
[](bg:base)\
($kubernetes)\
($gcloud)\
($cmd_duration)\
($status)\
"""

add_newline = true

palette = 'rose-pine-moon'

[palettes.rose-pine-moon]
base    = '#232136'
foam    = '#9ccfd8'
gold    = '#f6c177'
hl_high = '#56526e'
hl_low  = '#2a283e'
hl_med  = '#44415a'
iris    = '#c4a7e7'
love    = '#eb6f92'
muted   = '#6e6a86'
overlay = '#393552'
pine    = '#3e8fb0'
rose    = '#ea9a97'
subtle  = '#908caa'
surface = '#2a273f'
text    = '#e0def4'

[line_break]
disabled = false

[character]
disabled                  = false
error_symbol              = '[ ](bold fg:love)'
success_symbol            = '[ ](bold fg:iris)'
vimcmd_replace_one_symbol = '[ REPLACE ](bold fg:base bg:pine)[](inverted fg:base bg:pine)'
vimcmd_replace_symbol     = '[ REPLACE ](bold fg:base bg:pine)[](inverted fg:base bg:pine)'
vimcmd_symbol             = '[ NORMAL ](bold fg:base bg:iris)[](inverted fg:base bg:iris)'
vimcmd_visual_symbol      = '[ VISUAL ](bold fg:base bg:rose)[](inverted fg:base bg:rose)'

[directory]
disabled          = false
format            = '([ $path ]($style))'
style             = 'fg:base bg:iris'
truncate_to_repo  = true
truncation_length = 3
truncation_symbol = '…'

[git_branch]
disabled          = false
format            = '([ $symbol$branch(:$remote_branch)]($style))'
style             = 'fg:iris bg:overlay'
symbol            = ' '
truncation_length = 32
truncation_symbol = '…'

[git_state]
disabled = false
format   = '([ $state($progress_current/$progress_total) ]($style))'
style    = 'fg:iris bg:overlay'

[git_status]
ahead      = '  ${count}'
behind     = '  ${count}'
conflicted = '  ${count}'
deleted    = ' 󰍶 ${count}'
disabled   = false
diverged   = '  ${ahead_count}  ${behind_count}'
format     = '([$ahead_behind ($conflicted$stashed$modified$renamed$deleted$staged$untracked )]($style))'
modified   = ' 󰛿 ${count}'
renamed    = ' 󱍸 ${count}'
staged     = ' 󰐗 ${count}'
stashed    = '  ${count}'
style      = 'fg:iris bg:overlay'
untracked  = ' 󰋗 ${count}'
up_to_date = ''

[golang]
format = '([ $symbol($version)(\[$mod_version\]) ]($style))'
style  = 'fg:muted bg:hl_low'
symbol = '󰟓 '

[python]
format        = '([ $symbol($version)( \[$virtualenv\]) ]($style))'
python_binary = ['python3']
style         = 'fg:muted bg:hl_low'
symbol        = ' '

[gcloud]
disabled = true
format   = '[](fg:prev_bg $style inverted)[$symbol($account\[$project\]) ]'
style    = 'fg:base bg:muted'
symbol   = '󱇶 '

[kubernetes]
disabled = false
format   = '[](fg:prev_bg $style inverted)[$symbol($context) ]($style)'
style    = 'fg:base bg:muted italic'
symbol   = '󱃾 '

[[kubernetes.contexts]]
context_pattern = ".*(prod|02).*"
style           = 'fg:base bg:rose italic'

[[kubernetes.contexts]]
context_pattern = ".*(pp|01).*"
style           = 'fg:base bg:gold italic'

[[kubernetes.contexts]]
context_pattern = ".*(dev|00).*"
style           = 'fg:base bg:pine italic'

[status]
disabled              = false
format                = '[](fg:prev_bg $style inverted)[$symbol $common_meaning$signal_name$maybe_int ]($style)'
map_symbol            = true
not_executable_symbol = ''
not_found_symbol      = '󰩋'
sigint_symbol         = '󰹆'
signal_symbol         = '󱐋'
style                 = 'fg:base bg:love italic'
success_symbol        = ''
symbol                = '󱇎'

[cmd_duration]
disabled = false
format   = '[](fg:prev_bg $style inverted)[󱎫 $duration ]($style)'
min_time = 5000
style    = 'fg:base bg:rose italic'

[time]
disabled        = false
format          = '[](inverted $style)[󱑂 $time UTC ]($style)'
style           = 'fg:base bg:hl_med italic'
time_format     = '%T'
utc_time_offset = '0'
