return {
  diagnostics = { error = '', warn = '', hint = '󰠠', info = '' },
  git = {
    added = '',
    modified = '',
    deleted = '',
    renamed = '',
    untracked = '',
    ignored = '',
    unstaged = '󰄱',
    staged = '',
    conflict = '',
  },
  animated = {
    spinner = {
      '⠋',
      '⠙',
      '⠚',
      '⠒',
      '⠂',
      '⠂',
      '⠒',
      '⠲',
      '⠴',
      '⠦',
      '⠖',
      '⠒',
      '⠐',
      '⠐',
      '⠒',
      '⠓',
      '⠋',
    },
  },
  neotree = { default = '󰈔', folder_closed = '󰉋', folder_open = '󰝰', folder_empty = '󰉖' },
}
