#? Config file for btop v. 1.3.x

# Rose Pine Moon theme (themes dir is resolved from XDG_CONFIG_HOME/btop/themes)
color_theme = "rose-pine-moon"
theme_background = True
truecolor = True
force_tty = False

# UI
vim_keys = True
rounded_corners = True
graph_symbol = "braille"
graph_symbol_cpu = "default"
graph_symbol_gpu = "default"
graph_symbol_mem = "default"
graph_symbol_net = "default"
graph_symbol_proc = "default"

# Layout
shown_boxes = "cpu mem net proc"
update_ms = 2000

# Process view
proc_sorting = "cpu lazy"
proc_reversed = False
proc_tree = False
proc_colors = True
proc_gradient = True
proc_per_core = True
proc_mem_bytes = True
proc_cpu_graphs = True
proc_info_smaps = False
proc_left = False
proc_filter_kernel = False

# CPU
cpu_graph_upper = "total"
cpu_graph_lower = "user"
cpu_invert_lower = True
cpu_single_graph = False
cpu_bottom = False
show_cpu_freq = True
clock_format = "%X"
background_update = True
custom_cpu_name = ""
disks_filter = ""

# Memory
mem_graphs = True
mem_below_net = False
zfs_arc_cached = True

# Network
net_download = 100
net_upload = 100
net_auto = True
net_sync = False
net_iface = ""

# Battery
show_battery = True
selected_battery = "Auto"
show_battery_watts = True

# Misc
log_level = "WARNING"
base_10_sizes = False
show_coretemp = True
gpu_mirror_graph = True
