#define TAPPING_TERM_PER_KEY
#define TAPPING_TERM 175
#define QUICK_TAP_TERM_PER_KEY
#define QUICK_TAP_TERM 100
#define PERMISSIVE_HOLD

#undef COMBO_TERM
#define COMBO_TERM 40
#define EXTRA_SHORT_COMBOS

#define GRAVE_ESC_ALT_OVERRIDE
#define GRAVE_ESC_CTRL_OVERRIDE
