# Wildcard to allow APM32 MCU
DFU_SUFFIX_ARGS = -v FFFF -p FFFF

BOOTMAGIC_ENABLE = yes
COMBO_ENABLE = yes
COMMAND_ENABLE = yes
LTO_ENABLE = yes
NKRO_ENABLE = yes

AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = no
LEADER_ENABLE = no
MOUSEKEY_ENABLE = no
RGBLIGHT_ENABLE = no
TAP_DANCE_ENABLE = no
