# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
background        = "#232136"
bright_foreground = "#e0def4"
dim_foreground    = "#908caa"
foreground        = "#e0def4"

[colors.cursor]
cursor = "#56526e"
text   = "#e0def4"

[colors.vi_mode_cursor]
cursor = "#56526e"
text   = "#e0def4"

[colors.search.matches]
background = "#393552"
foreground = "#908caa"

[colors.search.focused_match]
background = "#ea9a97"
foreground = "#232136"

[colors.hints.start]
background = "#2a273f"
foreground = "#908caa"

[colors.hints.end]
background = "#2a273f"
foreground = "#6e6a86"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.footer_bar]
background = "#2a273f"
foreground = "#e0def4"

[colors.selection]
background = "#44415a"
text       = "#e0def4"

[colors.normal]
black   = "#393552"
blue    = "#9ccfd8"
cyan    = "#ea9a97"
green   = "#3e8fb0"
magenta = "#c4a7e7"
red     = "#eb6f92"
white   = "#e0def4"
yellow  = "#f6c177"

[colors.bright]
black   = "#6e6a86"
blue    = "#9ccfd8"
cyan    = "#ea9a97"
green   = "#3e8fb0"
magenta = "#c4a7e7"
red     = "#eb6f92"
white   = "#e0def4"
yellow  = "#f6c177"

[colors.dim]
black   = "#6e6a86"
blue    = "#9ccfd8"
cyan    = "#ea9a97"
green   = "#3e8fb0"
magenta = "#c4a7e7"
red     = "#eb6f92"
white   = "#e0def4"
yellow  = "#f6c177"
