# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
background        = "#191724"
bright_foreground = "#e0def4"
dim_foreground    = "#908caa"
foreground        = "#e0def4"

[colors.cursor]
cursor = "#524f67"
text   = "#e0def4"

[colors.vi_mode_cursor]
cursor = "#524f67"
text   = "#e0def4"

[colors.search.matches]
background = "#26233a"
foreground = "#908caa"

[colors.search.focused_match]
background = "#ebbcba"
foreground = "#191724"

[colors.hints.start]
background = "#1f1d2e"
foreground = "#908caa"

[colors.hints.end]
background = "#1f1d2e"
foreground = "#6e6a86"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.footer_bar]
background = "#1f1d2e"
foreground = "#e0def4"

[colors.selection]
background = "#403d52"
text       = "#e0def4"

[colors.normal]
black   = "#26233a"
blue    = "#9ccfd8"
cyan    = "#ebbcba"
green   = "#31748f"
magenta = "#c4a7e7"
red     = "#eb6f92"
white   = "#e0def4"
yellow  = "#f6c177"

[colors.bright]
black   = "#6e6a86"
blue    = "#9ccfd8"
cyan    = "#ebbcba"
green   = "#31748f"
magenta = "#c4a7e7"
red     = "#eb6f92"
white   = "#e0def4"
yellow  = "#f6c177"

[colors.dim]
black   = "#6e6a86"
blue    = "#9ccfd8"
cyan    = "#ebbcba"
green   = "#31748f"
magenta = "#c4a7e7"
red     = "#eb6f92"
white   = "#e0def4"
yellow  = "#f6c177"
