# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

[colors.primary]
background        = "#faf4ed"
bright_foreground = "#575279"
dim_foreground    = "#797593"
foreground        = "#575279"

[colors.cursor]
cursor = "#cecacd"
text   = "#575279"

[colors.vi_mode_cursor]
cursor = "#cecacd"
text   = "#575279"

[colors.search.matches]
background = "#f2e9e1"
foreground = "#797593"

[colors.search.focused_match]
background = "#d7827e"
foreground = "#faf4ed"

[colors.hints.start]
background = "#fffaf3"
foreground = "#797593"

[colors.hints.end]
background = "#fffaf3"
foreground = "#9893a5"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.footer_bar]
background = "#fffaf3"
foreground = "#575279"

[colors.selection]
background = "#dfdad9"
text       = "#575279"

[colors.normal]
black   = "#f2e9e1"
blue    = "#56949f"
cyan    = "#d7827e"
green   = "#286983"
magenta = "#907aa9"
red     = "#b4637a"
white   = "#575279"
yellow  = "#ea9d34"

[colors.bright]
black   = "#9893a5"
blue    = "#56949f"
cyan    = "#d7827e"
green   = "#286983"
magenta = "#907aa9"
red     = "#b4637a"
white   = "#575279"
yellow  = "#ea9d34"

[colors.dim]
black   = "#9893a5"
blue    = "#56949f"
cyan    = "#d7827e"
green   = "#286983"
magenta = "#907aa9"
red     = "#b4637a"
white   = "#575279"
yellow  = "#ea9d34"
