# Rose Pine Moon — atuin configuration
# https://github.com/atuinsh/atuin

dialect = "us"
auto_sync = false
update_check = false
sync_frequency = "1h"
sync_address = "https://api.atuin.sh"

# Search
search_mode = "fuzzy"
filter_mode = "global"
filter_mode_shell_up_key_binding = "session"

# UI
style = "compact"
inline_height = 20
show_preview = true
max_preview_height = 4
show_help = false
show_tabs = true
exit_mode = "return-query"
enter_accept = false

# History
history_filter = [
  "^ls$",
  "^cd$",
  "^pwd$",
  "^clear$",
  "^exit$",
]

[stats]
common_subcommands = [
  "cargo",
  "docker",
  "fish",
  "git",
  "go",
  "helm",
  "kubectl",
  "nvim",
  "terraform",
  "brew",
]
common_prefix = ["sudo"]
