# Path
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

# Term
export TERM="xterm-256color"

# editing
export PAGER="less"
export LESS="--ignore-case --raw-control-chars --chop-long-lines --LONG-PROMPT --SILENT"
export EDITOR="vim"
export VISUAL=$EDITOR
export USE_EDITOR=$EDITOR

# Local
if [[ -r ~/.localrc ]]; then
  source ~/.localrc
fi
